### ISSUE TITLE
Request new support for RTL8720CN

### ISSUE THREAD

**Issue by plplaaa2** [libretiny-eu/libretiny#303] opened 2024-12-07 02:24 UTC
Some Xiaomi devices currently use ESP32 as a communication chip. Esphome firmware is available for these devices.

[https://github.com/dhewg/esphome-miot](url)

But there are some Xiaomi devices that use a module called MHCWB4P, which is based on RTL8720CN.

![image](https://github.com/user-attachments/assets/4c080af4-be14-4d1e-a8b3-31c86e1dbd2d)

DATASHEET
[https://fcc.report/FCC-ID/2AFZZMHCWB4P-IB/4724540.pdf](url)

If possible, many Xiaomi devices will be released from the Mi app and made available locally.

**Comment by kuba2k2** [comment] 2024-12-07 08:49
Duplicate of #44.

**Closed** 2024-12-13 07:22 UTC
